source 'https://rubygems.org'

gem 'webrick', '~> 1.9'
gem 'dotenv', '~> 3.0'
gem 'rack', '~> 3.2'
gem 'rackup', '~> 2.2'
gem 'rubocop', require: false
gem 'pg', '~> 1.5'
gem 'grpc', '~> 1.76'
gem "grpc-tools", "~> 1.76"
gem "google-protobuf", "~> 3.25.8"
gem 'base64', '~> 0.1.0'