FROM docker.io/library/python:3.11-slim
WORKDIR /app

COPY pyproject.toml ./
RUN pip install poetry && poetry install --no-root

COPY proto-context/ ./proto_context/

ENV PYTHONPATH="/app/proto_context:${PYTHONPATH}"

COPY . .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
